name: taulight
description: "Messenger"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  uuid: ^4.5.1
  flutter_secure_storage: ^9.2.4
  collection: ^1.19.1
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  swipeable_tile: ^2.0.1
  mobile_scanner: ^6.0.10
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  share_plus: ^11.0.0
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^12.0.0+1
  mime_type: ^1.0.1
  file_picker: ^10.2.0
  open_file: ^3.5.10
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
